/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/Pharmacies': {
    get: {
      parameters: {
        header: {
          /** Api Request header */
          'X-Api-Request': string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'text/plain': components['schemas']['GetPharmaciesDTO'];
            'application/json': components['schemas']['GetPharmaciesDTO'];
            'text/json': components['schemas']['GetPharmaciesDTO'];
          };
        };
      };
    };
    post: {
      parameters: {
        header: {
          /** Api Request header */
          'X-Api-Request': string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
      requestBody: {
        content: {
          'application/json-patch+json': components['schemas']['CreatePharmacyDTO'];
          'application/json': components['schemas']['CreatePharmacyDTO'];
          'text/json': components['schemas']['CreatePharmacyDTO'];
          'application/*+json': components['schemas']['CreatePharmacyDTO'];
        };
      };
    };
  };
  '/api/v1/Pharmacies/{id}': {
    get: {
      parameters: {
        path: {
          id: number;
        };
        header: {
          /** Api Request header */
          'X-Api-Request': string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'text/plain': components['schemas']['GetPharmacyDTO'];
            'application/json': components['schemas']['GetPharmacyDTO'];
            'text/json': components['schemas']['GetPharmacyDTO'];
          };
        };
      };
    };
  };
  '/api/v1': {
    get: {
      parameters: {
        header: {
          /** Api Request header */
          'X-Api-Request': string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['MessageDTO'];
          };
        };
      };
    };
  };
}

export interface components {
  schemas: {
    CreatePharmacyDTO: {
      address?: string | null;
      city?: string | null;
      workingHours?: components['schemas']['WorkingHoursDTO'][] | null;
    };
    GetPharmacyDTO: {
      meta?: components['schemas']['Meta'];
      data?: components['schemas']['PharmacyFullDTO'];
    };
    GetPharmaciesDTO: {
      meta?: components['schemas']['Meta'];
      data?: components['schemas']['PharmacyDTO'][] | null;
    };
    MessageData: {
      message?: string | null;
    };
    MessageDTO: {
      meta?: components['schemas']['Meta'];
      data?: components['schemas']['MessageData'];
    };
    Meta: { [key: string]: unknown };
    PharmacyDTO: {
      pharmacyNo?: number;
      address?: string | null;
      city?: string | null;
    };
    PharmacyFullDTO: {
      workingHours?: components['schemas']['WorkingHoursDTO'][] | null;
      pharmacyNo?: number;
      address?: string | null;
      city?: string | null;
    };
    WorkingHoursDTO: {
      openTime?: string | null;
      closeTime?: string | null;
      dayOfWeek?: number;
    };
  };
}

// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface operations {}
