/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/Medicaments': {
    get: {
      parameters: {
        header: {
          /** Api Request header */
          'X-Api-Request': string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'text/plain': components['schemas']['MedicamentDTOGetListDTO'];
            'application/json': components['schemas']['MedicamentDTOGetListDTO'];
            'text/json': components['schemas']['MedicamentDTOGetListDTO'];
          };
        };
      };
    };
    post: {
      parameters: {
        header: {
          /** Api Request header */
          'X-Api-Request': string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
      requestBody: {
        content: {
          'application/json-patch+json': components['schemas']['CreateMedicamentDTO'];
          'application/json': components['schemas']['CreateMedicamentDTO'];
          'text/json': components['schemas']['CreateMedicamentDTO'];
          'application/*+json': components['schemas']['CreateMedicamentDTO'];
        };
      };
    };
  };
  '/api/v1/Medicaments/{id}': {
    get: {
      parameters: {
        path: {
          id: number;
        };
        header: {
          /** Api Request header */
          'X-Api-Request': string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'text/plain': components['schemas']['MedicamentFullDTOGetObjectDTO'];
            'application/json': components['schemas']['MedicamentFullDTOGetObjectDTO'];
            'text/json': components['schemas']['MedicamentFullDTOGetObjectDTO'];
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: number;
        };
        header: {
          /** Api Request header */
          'X-Api-Request': string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
      requestBody: {
        content: {
          'application/json-patch+json': components['schemas']['EditMedicamentDTO'];
          'application/json': components['schemas']['EditMedicamentDTO'];
          'text/json': components['schemas']['EditMedicamentDTO'];
          'application/*+json': components['schemas']['EditMedicamentDTO'];
        };
      };
    };
    delete: {
      parameters: {
        path: {
          id: number;
        };
        header: {
          /** Api Request header */
          'X-Api-Request': string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  '/api/v1/Orders': {
    get: {
      parameters: {
        header: {
          /** Api Request header */
          'X-Api-Request': string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'text/plain': components['schemas']['OrderDTOGetListDTO'];
            'application/json': components['schemas']['OrderDTOGetListDTO'];
            'text/json': components['schemas']['OrderDTOGetListDTO'];
          };
        };
      };
    };
    post: {
      parameters: {
        header: {
          /** Api Request header */
          'X-Api-Request': string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
      requestBody: {
        content: {
          'application/json-patch+json': components['schemas']['CreateOrderDTO'];
          'application/json': components['schemas']['CreateOrderDTO'];
          'text/json': components['schemas']['CreateOrderDTO'];
          'application/*+json': components['schemas']['CreateOrderDTO'];
        };
      };
    };
  };
  '/api/v1/Orders/{id}': {
    get: {
      parameters: {
        path: {
          id: number;
        };
        header: {
          /** Api Request header */
          'X-Api-Request': string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'text/plain': components['schemas']['OrderFullDTOGetObjectDTO'];
            'application/json': components['schemas']['OrderFullDTOGetObjectDTO'];
            'text/json': components['schemas']['OrderFullDTOGetObjectDTO'];
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: number;
        };
        header: {
          /** Api Request header */
          'X-Api-Request': string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
      requestBody: {
        content: {
          'application/json-patch+json': components['schemas']['TransactionProductDTO'][];
          'application/json': components['schemas']['TransactionProductDTO'][];
          'text/json': components['schemas']['TransactionProductDTO'][];
          'application/*+json': components['schemas']['TransactionProductDTO'][];
        };
      };
    };
  };
  '/api/v1/Orders/{id}/approve': {
    post: {
      parameters: {
        path: {
          id: number;
        };
        header: {
          /** Api Request header */
          'X-Api-Request': string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  '/api/v1/Orders/{id}/prepare': {
    post: {
      parameters: {
        path: {
          id: number;
        };
        header: {
          /** Api Request header */
          'X-Api-Request': string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  '/api/v1/PaymentTypes': {
    get: {
      parameters: {
        header: {
          /** Api Request header */
          'X-Api-Request': string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'text/plain': components['schemas']['EnumDTOGetListDTO'];
            'application/json': components['schemas']['EnumDTOGetListDTO'];
            'text/json': components['schemas']['EnumDTOGetListDTO'];
          };
        };
      };
    };
  };
  '/api/v1/PharmaceuticalForms': {
    get: {
      parameters: {
        header: {
          /** Api Request header */
          'X-Api-Request': string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'text/plain': components['schemas']['EnumDTOGetListDTO'];
            'application/json': components['schemas']['EnumDTOGetListDTO'];
            'text/json': components['schemas']['EnumDTOGetListDTO'];
          };
        };
      };
    };
  };
  '/api/v1/Pharmacies': {
    get: {
      parameters: {
        header: {
          /** Api Request header */
          'X-Api-Request': string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'text/plain': components['schemas']['PharmacyDTOGetListDTO'];
            'application/json': components['schemas']['PharmacyDTOGetListDTO'];
            'text/json': components['schemas']['PharmacyDTOGetListDTO'];
          };
        };
      };
    };
    post: {
      parameters: {
        header: {
          /** Api Request header */
          'X-Api-Request': string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
      requestBody: {
        content: {
          'application/json-patch+json': components['schemas']['CreatePharmacyDTO'];
          'application/json': components['schemas']['CreatePharmacyDTO'];
          'text/json': components['schemas']['CreatePharmacyDTO'];
          'application/*+json': components['schemas']['CreatePharmacyDTO'];
        };
      };
    };
  };
  '/api/v1/Pharmacies/all': {
    get: {
      parameters: {
        header: {
          /** Api Request header */
          'X-Api-Request': string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'text/plain': components['schemas']['PharmacyDTOGetListDTO'];
            'application/json': components['schemas']['PharmacyDTOGetListDTO'];
            'text/json': components['schemas']['PharmacyDTOGetListDTO'];
          };
        };
      };
    };
  };
  '/api/v1/Pharmacies/{id}': {
    get: {
      parameters: {
        path: {
          id: number;
        };
        header: {
          /** Api Request header */
          'X-Api-Request': string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'text/plain': components['schemas']['PharmacyFullDTOGetObjectDTO'];
            'application/json': components['schemas']['PharmacyFullDTOGetObjectDTO'];
            'text/json': components['schemas']['PharmacyFullDTOGetObjectDTO'];
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: number;
        };
        header: {
          /** Api Request header */
          'X-Api-Request': string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
      requestBody: {
        content: {
          'application/json-patch+json': components['schemas']['EditPharmacyDTO'];
          'application/json': components['schemas']['EditPharmacyDTO'];
          'text/json': components['schemas']['EditPharmacyDTO'];
          'application/*+json': components['schemas']['EditPharmacyDTO'];
        };
      };
    };
    delete: {
      parameters: {
        path: {
          id: number;
        };
        header: {
          /** Api Request header */
          'X-Api-Request': string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  '/api/v1/Pharmacies/{id}/products': {
    get: {
      parameters: {
        path: {
          id: number;
        };
        header: {
          /** Api Request header */
          'X-Api-Request': string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'text/plain': components['schemas']['ProductBalanceDTOGetListDTO'];
            'application/json': components['schemas']['ProductBalanceDTOGetListDTO'];
            'text/json': components['schemas']['ProductBalanceDTOGetListDTO'];
          };
        };
      };
    };
  };
  '/api/v1/Pharmacies/{id}/transactions': {
    get: {
      parameters: {
        path: {
          id: number;
        };
        header: {
          /** Api Request header */
          'X-Api-Request': string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'text/plain': components['schemas']['TransactionDTOGetListDTO'];
            'application/json': components['schemas']['TransactionDTOGetListDTO'];
            'text/json': components['schemas']['TransactionDTOGetListDTO'];
          };
        };
      };
    };
  };
  '/api/v1/Products': {
    get: {
      parameters: {
        header: {
          /** Api Request header */
          'X-Api-Request': string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'text/plain': components['schemas']['ProductBalanceDTOGetListDTO'];
            'application/json': components['schemas']['ProductBalanceDTOGetListDTO'];
            'text/json': components['schemas']['ProductBalanceDTOGetListDTO'];
          };
        };
      };
    };
  };
  '/api/v1/Transactions': {
    post: {
      parameters: {
        header: {
          /** Api Request header */
          'X-Api-Request': string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
      requestBody: {
        content: {
          'application/json-patch+json': components['schemas']['CreateTransactionDTO'];
          'application/json': components['schemas']['CreateTransactionDTO'];
          'text/json': components['schemas']['CreateTransactionDTO'];
          'application/*+json': components['schemas']['CreateTransactionDTO'];
        };
      };
    };
  };
  '/api/v1/Users': {
    get: {
      parameters: {
        header: {
          /** Api Request header */
          'X-Api-Request': string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'text/plain': components['schemas']['UserDTOGetListDTO'];
            'application/json': components['schemas']['UserDTOGetListDTO'];
            'text/json': components['schemas']['UserDTOGetListDTO'];
          };
        };
      };
    };
  };
  '/api/v1/Users/{id}': {
    get: {
      parameters: {
        path: {
          id: number;
        };
        header: {
          /** Api Request header */
          'X-Api-Request': string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'text/plain': components['schemas']['UserFullDTOGetObjectDTO'];
            'application/json': components['schemas']['UserFullDTOGetObjectDTO'];
            'text/json': components['schemas']['UserFullDTOGetObjectDTO'];
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: number;
        };
        header: {
          /** Api Request header */
          'X-Api-Request': string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
      requestBody: {
        content: {
          'application/json-patch+json': components['schemas']['EditUserDTO'];
          'application/json': components['schemas']['EditUserDTO'];
          'text/json': components['schemas']['EditUserDTO'];
          'application/*+json': components['schemas']['EditUserDTO'];
        };
      };
    };
  };
  '/api/v1/Users/me': {
    get: {
      parameters: {
        header: {
          /** Api Request header */
          'X-Api-Request': string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'text/plain': components['schemas']['UserFullDTOGetObjectDTO'];
            'application/json': components['schemas']['UserFullDTOGetObjectDTO'];
            'text/json': components['schemas']['UserFullDTOGetObjectDTO'];
          };
        };
      };
    };
  };
  '/api/v1/Users/login': {
    post: {
      parameters: {
        header: {
          /** Api Request header */
          'X-Api-Request': string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
      requestBody: {
        content: {
          'application/json-patch+json': components['schemas']['LoginDTO'];
          'application/json': components['schemas']['LoginDTO'];
          'text/json': components['schemas']['LoginDTO'];
          'application/*+json': components['schemas']['LoginDTO'];
        };
      };
    };
  };
  '/api/v1/Users/signup': {
    post: {
      parameters: {
        header: {
          /** Api Request header */
          'X-Api-Request': string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
      requestBody: {
        content: {
          'application/json-patch+json': components['schemas']['CreateUserDTO'];
          'application/json': components['schemas']['CreateUserDTO'];
          'text/json': components['schemas']['CreateUserDTO'];
          'application/*+json': components['schemas']['CreateUserDTO'];
        };
      };
    };
  };
  '/api/v1/Warehouses': {
    get: {
      parameters: {
        header: {
          /** Api Request header */
          'X-Api-Request': string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'text/plain': components['schemas']['WarehouseDTOGetListDTO'];
            'application/json': components['schemas']['WarehouseDTOGetListDTO'];
            'text/json': components['schemas']['WarehouseDTOGetListDTO'];
          };
        };
      };
    };
  };
  '/api/v1/Warehouses/{id}': {
    get: {
      parameters: {
        path: {
          id: number;
        };
        header: {
          /** Api Request header */
          'X-Api-Request': string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'text/plain': components['schemas']['WarehouseDTOGetObjectDTO'];
            'application/json': components['schemas']['WarehouseDTOGetObjectDTO'];
            'text/json': components['schemas']['WarehouseDTOGetObjectDTO'];
          };
        };
      };
    };
  };
  '/api/v1/Warehouses/{id}/products': {
    get: {
      parameters: {
        path: {
          id: number;
        };
        header: {
          /** Api Request header */
          'X-Api-Request': string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'text/plain': components['schemas']['ProductBalanceDTOGetListDTO'];
            'application/json': components['schemas']['ProductBalanceDTOGetListDTO'];
            'text/json': components['schemas']['ProductBalanceDTOGetListDTO'];
          };
        };
      };
    };
  };
  '/api/v1': {
    get: {
      parameters: {
        header: {
          /** Api Request header */
          'X-Api-Request': string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['MessageDTO'];
          };
        };
      };
    };
  };
}

export interface components {
  schemas: {
    CreateMedicamentDTO: {
      name?: string | null;
      activeSubstance?: string | null;
      barCode?: string | null;
      pharmaceuticalFormId?: number;
      country?: string | null;
      isPrescriptionRequired?: boolean;
      basePrice?: number;
      surcharge?: number;
      isReimbursed?: boolean;
      reimbursePercentage?: number | null;
    };
    CreateOrderDTO: {
      warehouseId?: number;
      products?: components['schemas']['TransactionProductDTO'][] | null;
    };
    CreatePharmacyDTO: {
      address?: string | null;
      city?: string | null;
      registersCount?: number;
      workingHours?: components['schemas']['WorkingHoursDTO'][] | null;
    };
    CreateTransactionDTO: {
      products?: components['schemas']['TransactionProductDTO'][] | null;
      pharmacyId?: number;
      registerId?: number;
      paymentTypeId?: number;
    };
    CreateUserDTO: {
      email?: string | null;
      password?: string | null;
      name?: string | null;
      surname?: string | null;
      position?: string | null;
      departmentId?: number;
      pharmacyId?: number | null;
      warehouseId?: number | null;
    };
    EditMedicamentDTO: {
      isPrescriptionRequired?: boolean | null;
      basePrice?: number | null;
      surcharge?: number | null;
      isReimbursed?: boolean | null;
      reimbursePercentage?: number | null;
    };
    EditPharmacyDTO: {
      address?: string | null;
      city?: string | null;
      workingHours?: components['schemas']['WorkingHoursDTO'][] | null;
    };
    EditUserDTO: {
      name?: string | null;
      surname?: string | null;
      position?: string | null;
      pharmacyId?: number | null;
      dismissalDate?: string | null;
      employeeStateId?: number | null;
    };
    EnumDTO: {
      id?: number;
      name?: string | null;
    };
    EnumDTOGetListDTO: {
      meta?: components['schemas']['Meta'];
      data?: components['schemas']['EnumDTO'][] | null;
    };
    LoginDTO: {
      email?: string | null;
      password?: string | null;
    };
    MedicamentDTO: {
      id?: number;
      name?: string | null;
      activeSubstance?: string | null;
      barCode?: string | null;
      price?: number;
      isPrescriptionRequired?: boolean;
    };
    MedicamentDTOGetListDTO: {
      meta?: components['schemas']['Meta'];
      data?: components['schemas']['MedicamentDTO'][] | null;
    };
    MedicamentFullDTO: {
      country?: string | null;
      manufacturer?: string | null;
      pharmaceuticalForm?: string | null;
      isReimbursed?: boolean;
      reimbursePercentage?: number;
      basePrice?: number;
      surcharge?: number;
      id?: number;
      name?: string | null;
      activeSubstance?: string | null;
      barCode?: string | null;
      price?: number;
      isPrescriptionRequired?: boolean;
    };
    MedicamentFullDTOGetObjectDTO: {
      meta?: components['schemas']['Meta'];
      data?: components['schemas']['MedicamentFullDTO'];
    };
    MessageData: {
      message?: string | null;
    };
    MessageDTO: {
      meta?: components['schemas']['Meta'];
      data?: components['schemas']['MessageData'];
    };
    Meta: { [key: string]: unknown };
    OrderDTO: {
      orderId?: number;
      addressFrom?: string | null;
      addressTo?: string | null;
      expectedDelivery?: string | null;
    };
    OrderDTOGetListDTO: {
      meta?: components['schemas']['Meta'];
      data?: components['schemas']['OrderDTO'][] | null;
    };
    OrderFullDTO: {
      products?: components['schemas']['ProductBalanceDTO'][] | null;
      total?: number;
      orderId?: number;
      addressFrom?: string | null;
      addressTo?: string | null;
      expectedDelivery?: string | null;
    };
    OrderFullDTOGetObjectDTO: {
      meta?: components['schemas']['Meta'];
      data?: components['schemas']['OrderFullDTO'];
    };
    PharmacyDTO: {
      pharmacyNo?: number;
      address?: string | null;
      city?: string | null;
    };
    PharmacyDTOGetListDTO: {
      meta?: components['schemas']['Meta'];
      data?: components['schemas']['PharmacyDTO'][] | null;
    };
    PharmacyFullDTO: {
      workingHours?: components['schemas']['WorkingHoursDTO'][] | null;
      registers?: components['schemas']['RegisterDTO'][] | null;
      pharmacyNo?: number;
      address?: string | null;
      city?: string | null;
    };
    PharmacyFullDTOGetObjectDTO: {
      meta?: components['schemas']['Meta'];
      data?: components['schemas']['PharmacyFullDTO'];
    };
    ProductBalanceDTO: {
      id?: number;
      medicamentName?: string | null;
      price?: number;
      amount?: number;
      expirationDate?: string | null;
    };
    ProductBalanceDTOGetListDTO: {
      meta?: components['schemas']['Meta'];
      data?: components['schemas']['ProductBalanceDTO'][] | null;
    };
    RegisterDTO: {
      id?: number;
      cash?: number;
    };
    TransactionDTO: {
      createdAt?: string | null;
      totalPrice?: number;
    };
    TransactionDTOGetListDTO: {
      meta?: components['schemas']['Meta'];
      data?: components['schemas']['TransactionDTO'][] | null;
    };
    TransactionProductDTO: {
      productBalanceId?: number;
      amount?: number;
    };
    UserDTO: {
      id?: number;
      name?: string | null;
      surname?: string | null;
      position?: string | null;
      department?: string | null;
    };
    UserDTOGetListDTO: {
      meta?: components['schemas']['Meta'];
      data?: components['schemas']['UserDTO'][] | null;
    };
    UserFullDTO: {
      registrationDate?: string;
      dismissalDate?: string | null;
      employeeState?: string | null;
      pharmacyId?: number | null;
      warehouseId?: number | null;
      id?: number;
      name?: string | null;
      surname?: string | null;
      position?: string | null;
      department?: string | null;
    };
    UserFullDTOGetObjectDTO: {
      meta?: components['schemas']['Meta'];
      data?: components['schemas']['UserFullDTO'];
    };
    WarehouseDTO: {
      id?: number;
      address?: string | null;
      city?: string | null;
    };
    WarehouseDTOGetListDTO: {
      meta?: components['schemas']['Meta'];
      data?: components['schemas']['WarehouseDTO'][] | null;
    };
    WarehouseDTOGetObjectDTO: {
      meta?: components['schemas']['Meta'];
      data?: components['schemas']['WarehouseDTO'];
    };
    WorkingHoursDTO: {
      openTime?: string | null;
      closeTime?: string | null;
      dayOfWeek?: number;
    };
  };
}

// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface operations {}
